# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: '%b %-d, %Y'

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github: jekyll
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'JSTracer: A JS Ray-Tracer'
email: dylan@ursatile.com
description: >- # this means to ignore newlines until "baseurl:"
  Material and code samples for Dylan Beattie's JavaScript ray-tracer workshop.
baseurl: '/jsray' # the subpath of your site, e.g. /blog
url: 'https://ursatile.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ursatile
github_username: ursatile

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules/
  # - examples/01-hello-world/node_modules
  # - examples/02-canvas/node_modules
  # - examples/03-tracer/node_modules
  # - examples/04-shapes/node_modules
  # - examples/05-lights/node_modules
  # - examples/06-more-shapes/node_modules
  # - examples/*/node_modules/
  # - examples/*/node_modules/*
  - examples/*/node_modules/**
